algoritmo "semnome"
var
   NU1, NU2: Real
Procedimento somador(A, B: Real)
             Inicio
                   EScreval("Recebi o valor", A)
                   Escreval("Recebi o valor", B)
                   Escreval("A soma deles é", A + B)
             Fimprocedimento
inicio
      Escreval("Digite um número:")
      Leia(NU1)
      Escreval("Digite um número:")
      Leia(NU2)
      somador(NU1, NU2)
fimalgoritmo
